name: Un pingüino curioso
title: Un pingüino curioso | Un blog escrito por Horacio M.
description: Un pingüino curioso es un blog en el que se tratan temas sobre informática. ¡Espero que os guste!
tags:
  - blog
  - Linux
  - Pingüino
  - GNU/Linux
  - h0r4ci0
  - Un pingüino curioso
show_hero: true
menu:
  - title: Home
    url: /
  - title: About me
    url: /aboutme
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: horamalean@protonmail.com
# See: https://disqus.com/
# disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id

# Theme
# version: v1.0.0 
